spring.application.name=paysnap

# PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/paysnap
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
#auth
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Stripe
stripe.secret=${STRIPE_SECRET}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

#email
spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA log
spring.jpa.show-sql=true